from typing import Any, Dict, List


def default_team_payloads() -> List[Dict[str, Any]]:
    return [
        {
            "team_id": "red",
            "internal_name": "Red Team",
            "bank_facing_name": "The Challengers",
            "color_token": "red",
            "mission_statement": "Simulate real-world fraudsters and evolve attacks.",
            "capability_tags": ["attack", "simulation", "mutation"],
            "default_agent_roles": ["Orchestrator", "Scenario Generator", "Executor"],
        },
        {
            "team_id": "blue",
            "internal_name": "Blue Team",
            "bank_facing_name": "The Defenders",
            "color_token": "blue",
            "mission_statement": "Detect, prevent, and respond to fraud in real time.",
            "capability_tags": ["detection", "response", "scoring"],
            "default_agent_roles": ["Orchestrator", "Rule Evaluator", "Decision Agent"],
        },
        {
            "team_id": "purple",
            "internal_name": "Purple Team",
            "bank_facing_name": "The Strategists",
            "color_token": "purple",
            "mission_statement": "Design strategies, rules, and threat models.",
            "capability_tags": ["strategy", "rule-design", "threat-model"],
            "default_agent_roles": ["Orchestrator", "Root Cause Analyst", "Rule Author"],
        },
        {
            "team_id": "green",
            "internal_name": "Green Team",
            "bank_facing_name": "The Builders",
            "color_token": "green",
            "mission_statement": "Implement strategies and rules into production code.",
            "capability_tags": ["implementation", "integration", "features"],
            "default_agent_roles": ["Orchestrator", "Rule-to-Code Translator", "Feature Engineer"],
        },
        {
            "team_id": "black",
            "internal_name": "Black Team",
            "bank_facing_name": "The Stressors",
            "color_token": "black",
            "mission_statement": "Stress test robustness and discover edge cases.",
            "capability_tags": ["chaos", "stress", "regression"],
            "default_agent_roles": ["Orchestrator", "Edge-Case Generator", "Chaos Injector"],
        },
        {
            "team_id": "orange",
            "internal_name": "Orange Team",
            "bank_facing_name": "The Gatekeepers",
            "color_token": "orange",
            "mission_statement": "Review, validate, and approve releases.",
            "capability_tags": ["review", "security", "release"],
            "default_agent_roles": ["Orchestrator", "Security Reviewer", "Release Assessor"],
        },
        {
            "team_id": "gold",
            "internal_name": "Gold Team",
            "bank_facing_name": "The Narrators",
            "color_token": "gold",
            "mission_statement": "Explain decisions with evidence and narratives.",
            "capability_tags": ["explainability", "narrative", "audit"],
            "default_agent_roles": ["Orchestrator", "Decision Explainer", "Evidence Trace"],
        },
        {
            "team_id": "white",
            "internal_name": "White Team",
            "bank_facing_name": "The Council",
            "color_token": "white",
            "mission_statement": "Ensure compliance, fairness, and audit readiness.",
            "capability_tags": ["compliance", "ethics", "audit"],
            "default_agent_roles": ["Orchestrator", "Policy Reviewer", "Compliance Auditor"],
        },
    ]


def default_agent_payloads() -> List[Dict[str, Any]]:
    return [
        {
            "agent_name": "Red Orchestrator",
            "team_id": "red",
            "role": "Campaign Manager",
            "capabilities": ["planning", "delegation", "attack-design"],
            "inputs": ["Scenario"],
            "outputs": ["AttackPlan"],
            "operating_mode": "auto",
            "guardrails": ["synthetic_only"],
        },
        {
            "agent_name": "Blue Orchestrator",
            "team_id": "blue",
            "role": "Defense Manager",
            "capabilities": ["detection", "decisioning", "response"],
            "inputs": ["Telemetry"],
            "outputs": ["Decision"],
            "operating_mode": "auto",
            "guardrails": ["synthetic_only"],
        },
        {
            "agent_name": "Purple Strategist",
            "team_id": "purple",
            "role": "Rule Author",
            "capabilities": ["rule-design", "analysis"],
            "inputs": ["Evidence", "Telemetry"],
            "outputs": ["RuleSpec"],
            "operating_mode": "semi-auto",
            "guardrails": ["synthetic_only"],
        },
        {
            "agent_name": "Green Builder",
            "team_id": "green",
            "role": "Rule-to-Code Translator",
            "capabilities": ["implementation", "testing"],
            "inputs": ["RuleSpec"],
            "outputs": ["Patch"],
            "operating_mode": "semi-auto",
            "guardrails": ["synthetic_only"],
        },
        {
            "agent_name": "Black Stressor",
            "team_id": "black",
            "role": "Chaos Injection",
            "capabilities": ["stress", "edge-cases"],
            "inputs": ["Patch"],
            "outputs": ["StressTestReport"],
            "operating_mode": "auto",
            "guardrails": ["synthetic_only"],
        },
        {
            "agent_name": "Orange Gatekeeper",
            "team_id": "orange",
            "role": "Release Reviewer",
            "capabilities": ["review", "approval"],
            "inputs": ["Patch", "TestEvidence"],
            "outputs": ["ApprovalDecision"],
            "operating_mode": "manual",
            "guardrails": ["synthetic_only"],
        },
        {
            "agent_name": "Gold Narrator",
            "team_id": "gold",
            "role": "Decision Explainer",
            "capabilities": ["xai", "narrative"],
            "inputs": ["Decision", "Evidence"],
            "outputs": ["ExplanationPack"],
            "operating_mode": "auto",
            "guardrails": ["synthetic_only"],
        },
        {
            "agent_name": "White Council",
            "team_id": "white",
            "role": "Compliance Auditor",
            "capabilities": ["compliance", "audit"],
            "inputs": ["ApprovalDecision", "Evidence"],
            "outputs": ["CompliancePack"],
            "operating_mode": "manual",
            "guardrails": ["synthetic_only"],
        },
    ]
