"""
Role-based access control mappings for Fraud Forge.
"""

from __future__ import annotations

from typing import Dict, Set


ROLE_SUPER_ADMIN = "super_admin"
ROLE_BANK_ADMIN = "bank_admin"
ROLE_FRAUD_OPERATOR = "bank_fraud_operator"
ROLE_FRAUD_ARCHITECT = "bank_fraud_architect"
ROLE_FRAUD_DEV = "bank_fraud_dev"
ROLE_TECH_LEAD = "bank_fraud_techlead"
ROLE_TECH_MANAGER = "bank_fraud_techmanager"
ROLE_AUDITOR = "bank_fraud_auditor"
ROLE_ANALYST = "analyst"

PERMISSIONS: Dict[str, Set[str]] = {
    ROLE_SUPER_ADMIN: {
        "agents:read",
        "agents:write",
        "ai:write",
        "auth:read",
        "battle:read",
        "battle:write",
        "evidence:read",
        "evidence:write",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "knowledge:write",
        "metrics:read",
        "rules:read",
        "rules:write",
        "rules:approve",
        "rules:deploy",
        "rsb:read",
        "rsb:write",
        "rsb:approve",
        "amc:read",
        "amc:write",
        "amc:approve",
        "approvals:read",
        "settings:read",
        "approvals:write",
        "approvals:decide",
        "workflow:read",
        "workflow:control",
        "rag:read",
        "rag:write",
        "audit:read",
        "seed:write",
        "settings:read",
        "settings:write",
        "teams:read",
        "teams:write",
        "tools:read",
        "tools:write",
        "xai:read",
        "xai:write",
    },
    ROLE_BANK_ADMIN: {
        "agents:read",
        "agents:write",
        "ai:write",
        "auth:read",
        "battle:read",
        "battle:write",
        "evidence:read",
        "evidence:write",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "settings:read",
        "knowledge:write",
        "metrics:read",
        "rules:read",
        "rules:write",
        "rules:approve",
        "rules:deploy",
        "rsb:read",
        "rsb:write",
        "rsb:approve",
        "amc:read",
        "amc:write",
        "amc:approve",
        "approvals:read",
        "approvals:write",
        "approvals:decide",
        "workflow:read",
        "workflow:control",
        "rag:read",
        "rag:write",
        "audit:read",
        "seed:write",
        "settings:read",
        "settings:write",
        "teams:read",
        "teams:write",
        "tools:read",
        "tools:write",
        "xai:read",
        "xai:write",
    },
    ROLE_FRAUD_OPERATOR: {
        "agents:read",
        "agents:write",
        "ai:write",
        "auth:read",
        "battle:read",
        "battle:write",
        "evidence:read",
        "evidence:write",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "knowledge:write",
        "metrics:read",
        "rules:read",
        "rsb:read",
        "amc:read",
        "approvals:read",
        "workflow:read",
        "workflow:control",
        "rag:read",
        "audit:read",
        "settings:read",
        "teams:read",
        "tools:read",
        "tools:write",
        "xai:read",
        "xai:write",
    },
    ROLE_FRAUD_ARCHITECT: {
        "agents:read",
        "agents:write",
        "ai:write",
        "auth:read",
        "battle:read",
        "evidence:read",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "knowledge:write",
        "metrics:read",
        "rules:read",
        "rules:write",
        "rules:approve",
        "rsb:read",
        "amc:read",
        "amc:write",
        "approvals:read",
        "workflow:read",
        "rag:read",
        "audit:read",
        "settings:read",
        "teams:read",
        "tools:read",
        "tools:write",
        "xai:read",
        "xai:write",
    },
    ROLE_FRAUD_DEV: {
        "agents:read",
        "agents:write",
        "ai:write",
        "auth:read",
        "battle:read",
        "evidence:read",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "knowledge:write",
        "metrics:read",
        "rules:read",
        "rules:write",
        "rsb:read",
        "rsb:write",
        "amc:read",
        "amc:write",
        "approvals:read",
        "workflow:read",
        "rag:read",
        "settings:read",
        "teams:read",
        "tools:read",
        "tools:write",
        "xai:read",
        "xai:write",
    },
    ROLE_TECH_LEAD: {
        "agents:read",
        "agents:write",
        "ai:write",
        "auth:read",
        "battle:read",
        "evidence:read",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "knowledge:write",
        "metrics:read",
        "rules:read",
        "rsb:read",
        "rsb:approve",
        "amc:read",
        "amc:approve",
        "approvals:read",
        "approvals:decide",
        "workflow:read",
        "rag:read",
        "audit:read",
        "settings:read",
        "teams:read",
        "tools:read",
        "tools:write",
        "xai:read",
        "xai:write",
    },
    ROLE_TECH_MANAGER: {
        "agents:read",
        "agents:write",
        "ai:write",
        "auth:read",
        "battle:read",
        "evidence:read",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "knowledge:write",
        "metrics:read",
        "rules:read",
        "rules:deploy",
        "rsb:read",
        "rsb:approve",
        "amc:read",
        "amc:approve",
        "approvals:read",
        "approvals:decide",
        "workflow:read",
        "workflow:control",
        "rag:read",
        "audit:read",
        "settings:read",
        "teams:read",
        "teams:write",
        "tools:read",
        "tools:write",
        "xai:read",
        "xai:write",
    },
    ROLE_AUDITOR: {
        "agents:read",
        "auth:read",
        "battle:read",
        "evidence:read",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "metrics:read",
        "rules:read",
        "rsb:read",
        "approvals:read",
        "workflow:read",
        "rag:read",
        "audit:read",
        "settings:read",
        "amc:read",
        "teams:read",
        "tools:read",
        "xai:read",
    },
    ROLE_ANALYST: {
        "agents:read",
        "auth:read",
        "battle:read",
        "evidence:read",
        "evaluation:read",
        "graph:read",
        "knowledge:read",
        "metrics:read",
        "rules:read",
        "rsb:read",
        "approvals:read",
        "workflow:read",
        "rag:read",
        "settings:read",
        "teams:read",
        "tools:read",
        "xai:read",
    },
}


def has_permission(role: str, permission: str) -> bool:
    """Return True if the role has the requested permission.

    Args:
        role: Role identifier.
        permission: Permission string.

    Returns:
        True when permission is allowed.
    """
    return permission in PERMISSIONS.get(role, set())
